// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: grpc/echo/echo.proto

package echo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	// 女
	Gender_FEMALE Gender = 0
	// 男
	Gender_MALE Gender = 1
	// 第三性别
	Gender_THIRD Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "FEMALE",
		1: "MALE",
		2: "THIRD",
	}
	Gender_value = map[string]int32{
		"FEMALE": 0,
		"MALE":   1,
		"THIRD":  2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_echo_echo_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_grpc_echo_echo_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_grpc_echo_echo_proto_rawDescGZIP(), []int{0}
}

// 结构
type EchoMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr          *Addr                  `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Gender        Gender                 `protobuf:"varint,6,opt,name=gender,proto3,enum=echo.voice.com.Gender" json:"gender,omitempty"`
	Hobby         []string               `protobuf:"bytes,7,rep,name=hobby,proto3" json:"hobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoMsg) Reset() {
	*x = EchoMsg{}
	mi := &file_grpc_echo_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMsg) ProtoMessage() {}

func (x *EchoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_echo_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMsg.ProtoReflect.Descriptor instead.
func (*EchoMsg) Descriptor() ([]byte, []int) {
	return file_grpc_echo_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EchoMsg) GetAddr() *Addr {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *EchoMsg) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *EchoMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EchoMsg) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_FEMALE
}

func (x *EchoMsg) GetHobby() []string {
	if x != nil {
		return x.Hobby
	}
	return nil
}

type Addr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      string                 `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addr) Reset() {
	*x = Addr{}
	mi := &file_grpc_echo_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addr) ProtoMessage() {}

func (x *Addr) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_echo_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addr.ProtoReflect.Descriptor instead.
func (*Addr) Descriptor() ([]byte, []int) {
	return file_grpc_echo_echo_proto_rawDescGZIP(), []int{1}
}

func (x *Addr) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Addr) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_grpc_echo_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_echo_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_echo_echo_proto_rawDescGZIP(), []int{2}
}

func (x *EchoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_grpc_echo_echo_proto protoreflect.FileDescriptor

const file_grpc_echo_echo_proto_rawDesc = "" +
	"\n" +
	"\x14grpc/echo/echo.proto\x12\x0eecho.voice.com\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\aEchoMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04addr\x18\x03 \x01(\v2\x14.echo.voice.com.AddrR\x04addr\x126\n" +
	"\bbirthday\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12.\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x16.echo.voice.com.GenderR\x06gender\x12\x14\n" +
	"\x05hobby\x18\a \x03(\tR\x05hobbyJ\x04\b\x02\x10\x03R\x03age\"6\n" +
	"\x04Addr\x12\x1a\n" +
	"\bprovince\x18\x01 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\"\x1e\n" +
	"\fEchoResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*)\n" +
	"\x06Gender\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\t\n" +
	"\x05THIRD\x10\x022\x96\x01\n" +
	"\x04Echo\x12?\n" +
	"\tUnaryEcho\x12\x17.echo.voice.com.EchoMsg\x1a\x17.echo.voice.com.EchoMsg\"\x00\x12M\n" +
	"\x10ClientStreamEcho\x12\x17.echo.voice.com.EchoMsg\x1a\x1c.echo.voice.com.EchoResponse\"\x00(\x01B\x13Z\x11go0base/grpc/echob\x06proto3"

var (
	file_grpc_echo_echo_proto_rawDescOnce sync.Once
	file_grpc_echo_echo_proto_rawDescData []byte
)

func file_grpc_echo_echo_proto_rawDescGZIP() []byte {
	file_grpc_echo_echo_proto_rawDescOnce.Do(func() {
		file_grpc_echo_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_echo_echo_proto_rawDesc), len(file_grpc_echo_echo_proto_rawDesc)))
	})
	return file_grpc_echo_echo_proto_rawDescData
}

var file_grpc_echo_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_echo_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_echo_echo_proto_goTypes = []any{
	(Gender)(0),                   // 0: echo.voice.com.Gender
	(*EchoMsg)(nil),               // 1: echo.voice.com.EchoMsg
	(*Addr)(nil),                  // 2: echo.voice.com.Addr
	(*EchoResponse)(nil),          // 3: echo.voice.com.EchoResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_grpc_echo_echo_proto_depIdxs = []int32{
	2, // 0: echo.voice.com.EchoMsg.addr:type_name -> echo.voice.com.Addr
	4, // 1: echo.voice.com.EchoMsg.birthday:type_name -> google.protobuf.Timestamp
	0, // 2: echo.voice.com.EchoMsg.gender:type_name -> echo.voice.com.Gender
	1, // 3: echo.voice.com.Echo.UnaryEcho:input_type -> echo.voice.com.EchoMsg
	1, // 4: echo.voice.com.Echo.ClientStreamEcho:input_type -> echo.voice.com.EchoMsg
	1, // 5: echo.voice.com.Echo.UnaryEcho:output_type -> echo.voice.com.EchoMsg
	3, // 6: echo.voice.com.Echo.ClientStreamEcho:output_type -> echo.voice.com.EchoResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_echo_echo_proto_init() }
func file_grpc_echo_echo_proto_init() {
	if File_grpc_echo_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_echo_echo_proto_rawDesc), len(file_grpc_echo_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_echo_echo_proto_goTypes,
		DependencyIndexes: file_grpc_echo_echo_proto_depIdxs,
		EnumInfos:         file_grpc_echo_echo_proto_enumTypes,
		MessageInfos:      file_grpc_echo_echo_proto_msgTypes,
	}.Build()
	File_grpc_echo_echo_proto = out.File
	file_grpc_echo_echo_proto_goTypes = nil
	file_grpc_echo_echo_proto_depIdxs = nil
}
